Repository Ddhruv-IOT/Embedded-Systems, pull requests merged in 2023-10, with the labels that each got.

#1 This code measure trash level in smart dustbin
  Trash_measurment.ino
Labels: hacktoberfest-accepted, hacktoberfest

#4 Code for robotic arm
  README.md
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#2 This code is used for opening and closing of flaps
  openclosesystem_octa.ino
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#3 created and edited servo control code
  servo_control/servo_control.ino
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#5 Add files via upload
  pir_industrial_cod.ino
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#6 Update README.md
  README.md
  progress bar.py
Labels: hacktoberfest-accepted, hacktoberfest
